-- Add draft support columns to posts
ALTER TABLE posts ADD COLUMN IF NOT EXISTS draft_content JSONB;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS has_draft BOOLEAN DEFAULT FALSE;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS draft_updated_at TIMESTAMPTZ;

-- Add draft support and missing features to pages
ALTER TABLE pages ADD COLUMN IF NOT EXISTS draft_content JSONB;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS has_draft BOOLEAN DEFAULT FALSE;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS draft_updated_at TIMESTAMPTZ;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS excerpt TEXT;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS published BOOLEAN DEFAULT TRUE;
